version: "3.7"

services:
  postgres:
    container_name: some-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data